language: node_js
node_js:
- '10.4'
before_install:
- pip install --user codecov
- npm install -g typescript
- npm install -g jasmine
script:
- npm install
- tsc
- nyc --reporter=lcov jasmine
after_success:
- codecov --file coverage/lcov.info --disable search